server.port=8090
server.servlet.session.timeout=60m

spring.application.name=console-web
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

management.endpoints.web.exposure.include=health,info

services.gateway.base-url=http://localhost:8080
services.organization-service.base-url=http://localhost:8082
services.auth-service.base-url=http://localhost:8081
services.product-service.base-url=http://localhost:8083
services.inventory-service.base-url=http://localhost:8084
services.billing-service.base-url=http://localhost:8085
services.payment-service.base-url=http://localhost:8086
services.accounting-service.base-url=http://localhost:8087
services.tax-service.base-url=http://localhost:8089
services.report-service.base-url=http://localhost:8088
services.customer-credit-service.base-url=http://localhost:9111
services.customer-service.base-url=http://localhost:9114
services.purchase-service.base-url=http://localhost:9109
services.sales-return-service.base-url=http://localhost:9110