server:
  port: 9111

spring:
  application:
    name: customer-credit-service
  datasource:
    url: jdbc:h2:file:./data/customer-credit-db;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
